---
- name: install vsftpd
  apt: name=vsftpd state=latest cache_valid_time=3600 update_cache=yes

- name: install libpam-pwdfile
  apt: name=libpam-pwdfile state=latest

- name: create directory for user configuration
  command: mkdir /etc/vsftpd.d creates=/etc/vsftpd.d

- name: create directory for key local_root from vsftpd.conf
  command: mkdir /srv/ftp creates=/srv/ftp

- name: set permissions for local_root
  command: chown root:root /srv/ftp

- name: copy file for PAM service
  template: src=vsftpd.pam.j2 dest=/etc/pam.d/vsftpd mode=644 backup=yes

- name: copy script the vsftpd-user
  template: src=vsftpd-user.j2 dest=/sbin/vsftpd-user mode=755

- name: add test user of the ftp
  tags: testuser
  command: /sbin/vsftpd-user add {{ test_user }} {{ test_user_password }} creates=/etc/vsftpd

# will be create backup file if already exist
- name: copy config file of the vsftpd
  template: src=vsftpd.conf.j2 dest=/etc/vsftpd.conf mode=644 backup=yes
  notify:
    - restart vsftpd
