---
- name: install
  apt: name=vsftpd state=latest cache_valid_time=3600 update_cache=yes

- name: install libpam-pwdfile
  apt: name=libpam-pwdfile state=latest

- name: create directory of the vsftpd
  command: mkdir {{ vsftpd_dir }} creates={{ vsftpd_dir }}

- name: copy file for PAM service
  template: src=vsftpd.j2 dest=/etc/pam.d/vsftpd mode=644

- name: copy script the vsftpd-user
  template: src=vsftpd-user.j2 dest=/sbin/vsftpd-user mode=755

- name: add test user of the ftp
  tags: testuser
  command: /sbin/vsftpd-user add {{ test_user }} {{ test_user_password }} creates={{ ftp_users_db }}

# will be create backup file if already exist
- name: copy config file of the vsftpd
  template: src=vsftpd.conf.j2 dest=/etc/vsftpd.conf mode=644 backup=yes
  notify:
    - restart vsftpd
